In [15]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

page = requests.get('https://www.officialcharts.com/charts/singles-chart/')
soup = BeautifulSoup(page.content, 'html.parser')

positions = soup.find_all('span', class_='position')
songs = soup.find_all('div', class_='title')
artists = soup.find_all('div', class_='artist')
labels = soup.find_all('span', class_='label')

data = []
for position, song, artist, label in zip(positions, songs, artists, labels):
    position_text = position.text.strip()
    song_text = song.text.strip()
    artist_text = artist.text.strip()
    label_text = label.text.strip()

    chart_data = {
        'Position': position_text,
        'Song': song_text,
        'Artist': artist_text,
        'Label': label_text
    }

    data.append(chart_data)

pd.DataFrame(data)

,Position,Song,Artist,Label
0,1,SPRINTER,DAVE & CENTRAL CEE,LIVE YOURS/NEIGHBOURHOOD
1,2,MIRACLE,CALVIN HARRIS/ELLIE GOULDING,COLUMBIA
2,3,GIVING ME,JAZZY,CHAOS
3,4,REACT,SWITCH DISCO & ELLA HENDERSON,RELENTLESS
4,5,DAYLIGHT,DAVID KUSHNER,MISERABLE MUSIC
...,...,...,...,...
95,96,LIVE MORE & LOVE MORE,CAT BURNS,SINCE 93
96,97,YELLOW,COLDPLAY,PARLOPHONE
97,98,UNDER YOU,FOO FIGHTERS,RCA
98,99,DOUBLE R'S,SLIM,WARNER RECORDS
99,100,S-CLASS,STRAY KIDS,INTERSCOPE

In [17]:
pd.DataFrame(data).to_excel('Official Singles Chart Top 100.xlsx')